import { Scale } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <nav className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-md">
        <div className="mx-auto max-w-3xl flex h-14 items-center justify-between px-4 sm:px-6">
          <a href="/" className="flex items-center gap-2.5">
            <img src="/logo.svg" alt="ScriptForge" className="size-7 rounded-lg" />
            <span className="text-sm font-bold tracking-tight">ScriptForge</span>
          </a>
        </div>
      </nav>

      {/* Content */}
      <main className="mx-auto max-w-3xl px-4 sm:px-6 py-10 sm:py-16">
        <div className="flex items-center gap-3 mb-2">
          <div className="flex size-10 items-center justify-center rounded-lg bg-primary/10">
            <Scale className="size-5 text-primary" />
          </div>
          <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        </div>
        <p className="text-sm text-muted-foreground mb-8">Last updated: July 25, 2025</p>

        <div className="prose prose-sm prose-neutral dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using ScriptForge (&ldquo;the Service&rdquo;), you agree to be bound by
              these Terms of Service. If you do not agree with any part of these terms, you must not
              use the Service. These terms apply to all users, including free and paid subscribers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. Description of Service</h2>
            <p>
              ScriptForge is an AI-powered YouTube script generation tool. We provide features
              including AI script generation, YouTube channel integration, comment reply generation,
              video metadata optimization, and project management. The Service is provided &ldquo;as is&rdquo;
              and we reserve the right to modify or discontinue any feature at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials.
              You must provide accurate information during registration and keep your account details
              up to date. You must be at least 13 years old to use the Service. You are responsible
              for all activities that occur under your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. Subscription & Payments</h2>
            <p>
              ScriptForge offers free and paid subscription plans. Pro plan subscriptions are billed
              through Stripe. Payments are non-refundable except as required by applicable law. We
              reserve the right to change pricing with reasonable notice. Your subscription will
              automatically renew at the end of each billing period unless cancelled before renewal.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. Usage Limits</h2>
            <p>
              Free accounts are subject to daily usage limits for project creation and AI generations.
              Pro accounts have higher or unlimited limits as specified in the plan details. We
              reserve the right to throttle or restrict accounts that abuse the Service, including
              automated or excessive requests.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">6. AI-Generated Content</h2>
            <p>
              Content generated by ScriptForge AI is provided for informational and creative purposes.
              You are responsible for reviewing, editing, and ensuring the accuracy and legality of
              any AI-generated content before publishing. ScriptForge is not liable for the content
              you create or publish using our tools.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">7. YouTube Integration</h2>
            <p>
              Connecting your YouTube channel requires granting ScriptForge permission to read
              channel data and statistics. We do not post content or make changes to your channel
              without your explicit action. You can disconnect your channel at any time from
              Settings. YouTube&rsquo;s own Terms of Service also apply to your use of their platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">8. Prohibited Use</h2>
            <p>You agree not to use ScriptForge to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Generate content that is illegal, harmful, threatening, abusive, or harassing.</li>
              <li>Create deepfakes, misinformation, or content designed to deceive.</li>
              <li>Scrape, hack, or attempt to gain unauthorized access to the Service or its systems.</li>
              <li>Resell, redistribute, or sublicense the Service without prior written consent.</li>
              <li>Use the Service in violation of YouTube&rsquo;s Terms of Service or Community Guidelines.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">9. Limitation of Liability</h2>
            <p>
              ScriptForge is not liable for any indirect, incidental, or consequential damages arising
              from your use of the Service, including but not limited to loss of data, revenue, or
              reputation. Our total liability shall not exceed the amount you paid for the Service
              in the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">10. Changes to Terms</h2>
            <p>
              We may update these Terms of Service from time to time. Material changes will be
              communicated via email or in-app notification. Continued use of the Service after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">11. Contact</h2>
            <p>
              For questions about these Terms, please contact us at
              {' '}<a href="mailto:support@scriptforge.app" className="text-primary hover:underline">support@scriptforge.app</a>.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-6">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted-foreground">
          <span>&copy; {new Date().getFullYear()} ScriptForge. All rights reserved.</span>
          <div className="flex items-center gap-4">
            <a href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</a>
            <a href="/terms" className="hover:text-foreground transition-colors">Terms of Service</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
