import { FileText } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <nav className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-md">
        <div className="mx-auto max-w-3xl flex h-14 items-center justify-between px-4 sm:px-6">
          <a href="/" className="flex items-center gap-2.5">
            <img src="/logo.svg" alt="ScriptForge" className="size-7 rounded-lg" />
            <span className="text-sm font-bold tracking-tight">ScriptForge</span>
          </a>
        </div>
      </nav>

      {/* Content */}
      <main className="mx-auto max-w-3xl px-4 sm:px-6 py-10 sm:py-16">
        <div className="flex items-center gap-3 mb-2">
          <div className="flex size-10 items-center justify-center rounded-lg bg-primary/10">
            <FileText className="size-5 text-primary" />
          </div>
          <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
        </div>
        <p className="text-sm text-muted-foreground mb-8">Last updated: July 25, 2025</p>

        <div className="prose prose-sm prose-neutral dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. Information We Collect</h2>
            <p>
              When you create an account, we collect your name, email address, and password (encrypted).
              If you sign in with Google, we receive your name and email from Google. If you connect your
              YouTube channel, we store your channel name, description, and statistics provided by the
              YouTube API. We do not store your YouTube password or OAuth tokens in plain text.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. How We Use Your Information</h2>
            <p>
              We use your information to provide and improve ScriptForge services, including generating
              AI scripts, managing your projects, and displaying channel analytics. Your email is used
              for account verification and important notifications about your account or subscription.
              We do not sell or share your personal data with third parties for marketing purposes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. Third-Party Services</h2>
            <p>
              ScriptForge integrates with the following third-party services:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li><strong className="text-foreground">Google Gemini API</strong> — for AI script generation and content analysis.</li>
              <li><strong className="text-foreground">YouTube Data API</strong> — to fetch channel stats and video data when you connect your channel.</li>
              <li><strong className="text-foreground">Google OAuth</strong> — for sign-in and YouTube account connection.</li>
              <li><strong className="text-foreground">Stripe</strong> — for payment processing if you purchase a Pro subscription.</li>
              <li><strong className="text-foreground">Brevo</strong> — for sending transactional emails (verification, notifications).</li>
            </ul>
            <p className="mt-2">
              Each of these services has their own privacy policies. We encourage you to review them.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. Data Storage & Security</h2>
            <p>
              Your data is stored in secure databases with encryption at rest. Passwords are hashed using
              industry-standard algorithms. We use HTTPS for all data transmission. Access to your data
              is restricted to authorized personnel only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. AI-Generated Content</h2>
            <p>
              Scripts and content generated by ScriptForge AI are based on your input and prompts.
              Content you generate is stored in your account and is your responsibility. We may use
              anonymized, aggregated data to improve our AI models and service quality.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">6. Your Rights</h2>
            <p>
              You have the right to access, modify, or delete your personal data at any time through
              the Settings page. You can also disconnect your YouTube channel, delete your account,
              or export your data by contacting us. If you have questions about your data, please reach
              out to our support team.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">7. Cookies</h2>
            <p>
              ScriptForge uses essential cookies for authentication (session tokens). We do not use
              tracking cookies or third-party advertising cookies. Your browser settings can be
              configured to block cookies, though this may affect functionality.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">8. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy or your data, please contact us at
              {' '}<a href="mailto:support@scriptforge.app" className="text-primary hover:underline">support@scriptforge.app</a>.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-6">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted-foreground">
          <span>&copy; {new Date().getFullYear()} ScriptForge. All rights reserved.</span>
          <div className="flex items-center gap-4">
            <a href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</a>
            <a href="/terms" className="hover:text-foreground transition-colors">Terms of Service</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
